# Generated by Django 5.0.4 on 2024-04-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_services_created_at_services_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
