# Generated by Django 5.0.4 on 2024-04-20 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_services_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='done',
            field=models.CharField(choices=[('accept', 'Bajarildi'), ('reject', 'Bajarilmadi'), ('delay', 'Kechiktirildi')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceDone',
        ),
    ]
