# Generated by Django 5.0.4 on 2024-04-20 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_queue_done_queue_user_delete_servicedone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(default=1, help_text='Xizmat ikon', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queue',
            name='done',
            field=models.CharField(choices=[('accept', 'Bajarildi'), ('reject', 'Bajarilmadi'), ('delay', 'Kechiktirildi'), ('waiting', 'Kutilmoqda')], help_text='Bajarilganlik holati', max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='first_name',
            field=models.CharField(help_text='Ism', max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='last_name',
            field=models.CharField(help_text='Familiya', max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='order_number',
            field=models.CharField(help_text='Buyurtma raqami', max_length=100),
        ),
        migrations.AlterField(
            model_name='queue',
            name='services',
            field=models.ForeignKey(blank=True, help_text='Xizmat turi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.services', verbose_name='Xizmat turi'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.CharField(help_text='Xizmat kodi', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(help_text='Xizmat nomi', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqti"),
        ),
    ]
