# Generated by Django 5.0.3 on 2024-04-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_queue_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Icon nomi', max_length=100)),
                ('url', models.CharField(help_text='Icon url', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqti")),
            ],
        ),
    ]
