# Generated by Django 5.0.3 on 2024-04-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_icons_url_icons_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.icons'),
        ),
    ]
